# Generated by Django 3.0.5 on 2020-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cust_info',
            fields=[
                ('invoice', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shirt', models.IntegerField()),
                ('pant', models.IntegerField()),
                ('Total_amount', models.IntegerField()),
                ('rem_amount', models.IntegerField()),
                ('recived_amount', models.IntegerField(blank=True, null=True)),
                ('delevery_date', models.DateField()),
                ('oder_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pant_de',
            fields=[
                ('invoice_p', models.IntegerField(primary_key=True, serialize=False)),
                ('name_p', models.CharField(max_length=100)),
                ('pl', models.IntegerField()),
                ('p_k', models.IntegerField()),
                ('ph1', models.IntegerField()),
                ('pg', models.IntegerField()),
                ('ph2', models.IntegerField()),
                ('p_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt_de',
            fields=[
                ('invoice_s', models.IntegerField(primary_key=True, serialize=False)),
                ('name_s', models.CharField(max_length=100)),
                ('sl', models.IntegerField()),
                ('sm1', models.IntegerField()),
                ('ss', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('sm2', models.IntegerField()),
                ('s_type', models.CharField(max_length=50)),
            ],
        ),
    ]
